language: python
python:
  - "3.3"
cache:
  directories:
    - $HOME/.pip-cache
install:
  - pip install flake8 --cache-dir $HOME/.pip-cache
  - pip install -r requirements.txt --use-mirrors --cache-dir $HOME/.pip-cache
before_script:
  - cp settings.py.sample settings.py
  - flake8 .
script:
  - python runtests.py
